### ISSUE TITLE
Migrating device tree to acpi table

### ISSUE THREAD

**Issue by arunbharadwaj** [westeri/meta-acpi#1]
Hi Mika,

First of all thanks for the great work. I am keenly following your meta-acpi layer because we (at Gumstix) are making custom Joule boards.

I am trying to add a .asl file to the meta-acpi layer for adding an RGB sensor on a Joule custom board and for some reason I can't get the driver to load. I have made sure that the necessary driver is being built into the kernel. I am attaching my .asl file below.

[isl29125.txt](https://github.com/westeri/meta-acpi/files/584115/isl29125.txt)

I suspect that I am not correctly following the steps needed to translate devicetree-like properties into asl-like properties. Any pointers you could give me regarding this would be really helpful. My apologies that I opened a new issue for this although this is not an issue with your meta-acpi layer but thought you might be the right person to help me.

thanks,
Arun

**Comment by westeri** [comment]
The driver itself needs to be supporting DT. I'm attaching hack patch that should work:

[isl29125-patch.txt](https://github.com/westeri/meta-acpi/files/585447/isl29125.txt)

Note you should use "isil," prefix with the compatible string so you need to fix your ASL accordingly. In addition to my hack, you need to add those bindings to Documentation/devicetree/bindings when you submit the driver changes to upstream.

BTW, Would you like to submit that isl29125.asl to meta-acpi samples? If yes, please send it to me as patch and I'll apply it.

**Comment by arunbharadwaj** [comment]
Ah, that makes more sense as to why the driver was not attaching. I will try your patch when I get a chance and will send you a pull request for the isl29125.asl along with a few other sensor samples that I am interested in. Thanks for your help!

Arun
