### ISSUE TITLE
Add edison machine support

### ISSUE THREAD

**Issue by alext-mkrs** [westeri/meta-acpi#10]
Following up on our discussion in https://github.com/westeri/meta-acpi/pull/7, summary [here](https://github.com/westeri/meta-acpi/pull/7#issuecomment-362898523).

We want to add basic `edison` machine support into `meta-acpi`. Relevant discussion excerpts are below

>Adding Edison MACHINE support - only sample ACPI tables and a way to bundle/activate them. Maybe in a way @htot proposed, loading through configfs + systemd service to do that. Alternative is loading from initramfs, but it's not clear whether that's possible (initial tests were unsuccessful). If systemd way is used - the recipe must use Yocto's systemd class to do proper build-time feature detection and unit file deployment without doing all of that manually

> meta-acpi is designed to support only initramfs approach for now. So, I'm totally to support configfs approach, but let's do this generic (good start, even before Edison) is to enable it for Galileo Gen 2.

**Comment by andy-shev** [comment]
Seems like it's done deal with @htot PR https://github.com/westeri/meta-acpi/pull/14.
