### ISSUE TITLE
Enable ACPI-enabled kernel build when kernel recipe is provided by BSP layer - Edison

### ISSUE THREAD

**Issue by alext-mkrs** [westeri/meta-acpi#12]
Following up on our discussion in https://github.com/westeri/meta-acpi/pull/7, summary [here](https://github.com/westeri/meta-acpi/pull/7#issuecomment-362898523).

Adding kernel overrides/appends for enabling ACPI build (and removing this piece from `meta-intel-edison`), just for Edison as the first step.

Relevant other quote (from @andy-shev):
> Yes, `meta-intel-edison`, from my point of view, should be clean out of ACPI related things and be just a continuation of not-so-standard-intel-platform-bsp. Of course, if you decide otherwise I'm not going to stop you.

**Comment by andy-shev** [comment]
Since ACPI is a part of x86 build (including Intel Edison), based on the https://github.com/westeri/meta-acpi/issues/11#issuecomment-706404819 from @htot and my own thought the kernel build can be done in certain layer without touching or involving meta-acpi. Closing as **won't fix**.
