### ISSUE TITLE
Can I set priority of ACPI table from Intel Edison?

### ISSUE THREAD

**Issue by bruce-wayne-tw** [westeri/meta-acpi#19]
Hi @andy-shev , 
In my case, SPIDEV is first. if possible set LEDS is first and i2c last or lazy load?

<img width="968" alt="截圖 2021-08-02 16 14 01" src="https://user-images.githubusercontent.com/12690796/127980479-34b429bb-a673-44eb-93b6-ce408e1b7bb4.png">

**Comment by htot** [comment]
Hi @sjpeng I think they can be loaded as like. If you are on edison, the tables would be loaded by this script: https://github.com/edison-fw/meta-acpi/blob/gatesgarth/recipes-bsp/acpi-tables/files/edison/acpi-tables-load.

**Comment by andy-shev** [comment]
@sjpeng 
They are loaded in order of appearance AFAIU (the order in how they are archived with initramfs). But the question is why to reorder? Do you have any issues with it? Can you please elaborate?

**Comment by bruce-wayne-tw** [comment]
@htot 
Thanks, it's work!

```
#!/bin/sh
# This script loads all ACPI tables from /kernel/firmware/acpi
# You must have configfs enabled for this to work

#find /kernel/firmware/acpi/ -type f -name "*.aml" 2>/dev/null | while read TABLE; do
#  dest_dir=$(basename $TABLE .aml)
#  mkdir /sys/kernel/config/acpi/table/$dest_dir
#  cat $TABLE >/sys/kernel/config/acpi/table/$dest_dir/aml
#done
#
#sleep 0.2
#gpioset $(gpiofind TRI_STATE_ALL)=0
#gpioset $(gpiofind TRI_STATE_ALL)=1

# spidev
mkdir /sys/kernel/config/acpi/table/spidev
cat /kernel/firmware/acpi/spidev.aml > /sys/kernel/config/acpi/table/spidev/aml
sleep 0.5

# gpio
mkdir /sys/kernel/config/acpi/table/gpio
cat /kernel/firmware/acpi/gpio.aml > /sys/kernel/config/acpi/table/gpio/aml
sleep 0.5

# i2c3028
mkdir /sys/kernel/config/acpi/table/i2c3028
cat /kernel/firmware/acpi/i2c3028.aml > /sys/kernel/config/acpi/table/i2c3028/aml
sleep 0.5

```


@andy-shev 
I have designed a multi-function board for Edison, but that was wrong of i2c device of power. The power control at the GPIO, so I need to provide power before i2c setup.

**Comment by andy-shev** [comment]
> @andy-shev
> I have designed a multi-function board for Edison, but that was wrong of i2c device of power. The power control at the GPIO, so I need to provide power before i2c setup.

This sounds weird. The GPIO for power line should be handled by the respective kernel driver. Or if you are doing this in user space? If you want to enforce dependencies, try `_DEP` method (but I think it will work only on very recent kernels, not sure about v5.10.y).

**Comment by andy-shev** [comment]
@sjpeng If you have code somewhere of the driver and schematics, or you able to share those (privately or publicly) I may help to understand the root cause. For now I don\'t see any bugs related to meta-acpi.
